name: Supabase DB Migrations

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: supabase
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Link project
        run: |
          supabase link \
            --project-ref "$SUPABASE_PROJECT_REF" \
            --password "$SUPABASE_DB_PASSWORD"

      - name: Repair migration history (mark initial as applied)
        run: |
          # Mark legacy initial migrations as applied on remote to avoid re-creating existing tables
          supabase migration repair --status applied 20250128_000001 20250128_000002 || true
          # Some projects store full names in history; try name variants as well
          supabase migration repair --status applied 20250128_000001_initial_setup 20250128_000002_storage_setup || true
          # Some setups use numeric timestamps without underscores (YYYYMMDDHHMMSS)
          supabase migration repair --status applied 20250128000001 20250128000002 || true

      - name: Push migrations
        run: |
          printf "y\n" | supabase db push --include-all
